[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npx prisma db push && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
